service: rsp-token-decrypt

custom:
  documentation:
    models:
      - name: DecryptRequest
        description: This is a decrypt request
        contentType: application/json
        schema: ${file(models/DecryptRequest.json)}
      - name: DecryptResponse
        description: This is a decrypt response
        contentType: application/json
        schema: ${file(models/DecryptResponse.json)}
      - name: ErrorResponse
        description: This is an error
        contentType: application/json
        schema: ${file(models/ErrorResponse.json)}
    version: '1'
    title: 'RSP Token Decryption API'
    description: 'This is an API to decrypt the token provided by the RSP mobile application'

plugins:
  - serverless-offline
  - serverless-openapi-documentation
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  environment:
    USE_SECRETS_MANAGER: "false"
    ENCRYPTION_PASSWORD: "password"
functions:
  decrypt:
    handler: decrypt/app.handler
    memorySize: 128
    events:
      -
        httpApi:
          path: /decrypt
          method: post
          authorizer:
            type: aws_iam
          documentation:
            summary: "Decrypt Token"
            description: "Decrypt Token"
            requestBody:
              description: "None"
            requestModels:
              application/json: "DecryptRequest"
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: "Message of successful Notification sent"
                responseModels:
                  application/json: "DecryptResponse"
              - statusCode: 400
                responseBody:
                  description: "Error message detailing why the token could not be decrypted"
                responseModels:
                  application/json: "ErrorResponse"
