name: Run Lambda Function Update
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: nonprod
        type: environment
      zip_archive:
        description: 'Enter the name of the zip object from S3 to deploy. Example: master.zip'
        required: true
        default: master.zip
        type: string

jobs:
  update-lambda-code:
    uses: dvsa/.github/.github/workflows/update-lambda-function.yaml@v2.2
    with:
      environment: ${{ github.event.inputs.environment }}
      lambda_function_name: rsp-nonprod-apis-token-decrypt
      bucket_key: token/decrypt/${{ needs.build-names.outputs.pretty_branch_name }}.zip
    permissions:
      id-token: write
    secrets:
      AWS_ACCOUNT: ${{ secrets.RSP_AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.RSP_AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
